- hosts: all
  tasks:
    - name: restart host
      shell: 'sleep 5 && shutdown -r now "[Ansible]: Reboot"'
      become: yes
      async: 1
      poll: 0

    - name: 'Wait for host to become available again'
      wait_for_connection:
        delay: 30
        connect_timeout: 10
        sleep: 10
        timeout: 300

